name: Check library requirements

on: [push, pull_request]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # replace with your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create requirements.txt
      run: pip freeze > requirements.txt

    - name: Check dependencies
      run: pip check
